import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyRouter from "@/module/layout/router";
import { ReactQueryClientProvider } from "@/module/layout/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <ReactQueryPvorider> */}
          <MyRouter>{children}</MyRouter>
          {/* </ReactQueryPvorider> */}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
